apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  storageClassName: "efs-sc" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    type: efs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: efs-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: eefs-dynamic
    persistentVolumeClaim:
      claimName: ebs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    type: eefs-dynamic
  ports:
    - port: 80              # External port to expose
      targetPort: 80     # Port on the Pod where the application listens
      nodePort: 30007
