apiVersion: v1
kind: Pod
metadata:
  name: labelstest
  labels:
    project: expense
    environment: dev
    org: joindevops
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80