apiVersion: v1
kind: Pod
metadata:
  name: annotationdemo
  annotations:
    devOpsURL: "https://fb.com"
    username: sunilN
    password: abc@123
spec:
  containers:
  - name: nginx
    image: nginx