apiVersion: v1
kind: Pod
metadata:
  name: envdemo
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env: 
    - name: environment
      valueFrom:
        configKeyRef:
          name: myconfigmap
          key: environmnet
    - name: location
      valueFrom:
        configKeyRef:
          name: myconfigmap
          key: location
    - name: DB_URL
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: db_url 