apiVersion: v1
kind: Pod
metadata:
  name: envdemo
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env: 
    - name: environment
      value: dev
    - name: DB_URL
        valueFrom:
          secretKeyRef:
            Name: mysecret
            key: DB_URL