apiVersion: v1
kind: Service
metadata: 
  name: samplecluster
spec:
  type: ClusterIP
  selector:
    project: expense
    environment: dev
    org: joindevops
  ports:
  - port: 80
    name: sample-service-port
    targetPort: 80