apiVersion: v1
kind: Service
metadata: 
  name: samplecluster
spec:
  selector:
    project: expense
    environment: dev
    org: joindevops
  ports:
  - name: sample-service-port
    protocol: TCP
    port: 80
    targetPort: 80
