apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    org: joindevops
  ports:
    - port: 80              # External port to expose
      targetPort: 80      # Port on the Pod where the application listens
