apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
    project: expense
    environment: dev
    org: joindevops
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
      project: expense
      environment: dev
      org: joindevops
  template:
    metadata:
      labels:
        tier: frontend
        app: guestbook
        project: expense
        environment: dev
        org: joindevops
    spec:
      containers:
      - name: nginx
        image: nginx