
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector:
    type: ebs-stateful
  ports:
    - port: 3306             # External port to expose
      targetPort: 3306     # Port on the Pod where the application listens
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-expense
  namespace: expense
spec:
  selector:
    type: ebs-stateful
  ports:
    - port: 3306             # External port to expose
      targetPort: 3306  
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql

spec:
  selector:
    matchLabels:
      type: ebs-stateful
  serviceName: "mysql-headless"
  replicas: 3 # by default is 1
  
  template:
    metadata:
      labels:
        type: ebs-stateful # has to match .spec.selector.matchLabels
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east-1b
      containers:
      - name: mysql
        image: sunil0428/mysql:v1
        ports:
        - containerPort: 3306
          name: ebs-stateful
        volumeMounts:
        - name: ebs-stateful
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: ebs-stateful
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs-sc"
      resources:
        requests:
          storage: 1Gi
